Repository microsoft/tsiclient, pull requests merged in 2020-12, with the labels that each got.

#294 Fixed marker tooltip positions
  pages/examples/testcases/tooltipPositioning.html
  src/UXClient/Components/Marker/Marker.ts
  src/UXClient/Components/Tooltip/Tooltip.ts
Labels: bugfix :bug: :white_check_mark:, small change :droplet:

#289 Swimlane labels
  pages/examples/testcases/swimLanes/swimLaneLabels.html
  src/UXClient/Components/LineChart/LineChart.scss
  src/UXClient/Components/LineChart/LineChart.ts
  src/UXClient/Components/LinePlot/LinePlot.scss
  src/UXClient/Components/LinePlot/LinePlot.ts
  src/UXClient/Constants/Constants.ts
  src/UXClient/Models/ChartOptions.ts
Labels: T7 dependency :link:, enhancement :bulb:

#296 Fixes analytics crash on swimlane options in T7
  src/UXClient/Components/LineChart/LineChart.ts
Labels: bugfix :bug: :white_check_mark:, small change :droplet:

#300 Hotfix to prevent targetElement.classed() calls from breaking on null element
  src/UXClient/Components/Marker/Marker.ts
  src/UXClient/Interfaces/Component.ts
Labels: bugfix :bug: :white_check_mark:, small change :droplet:

#290 User/iremay/reference data
  pages/examples/testcases/postBatchReferenceData.html
  src/ServerClient/ServerClient.ts
  src/UXClient/Constants/Enums.ts
  src/UXClient/Utils.ts
Labels: T7 dependency :link:, enhancement :bulb:, review needed :pray::mag_right:

#303 Negative height bugfix
  src/UXClient/Components/AvailabilityChart/AvailabilityChart.ts
  src/UXClient/Components/CategoricalPlot/CategoricalPlot.ts
  src/UXClient/Components/HeatmapCanvas/HeatmapCanvas.ts
  src/UXClient/Components/LineChart/LineChart.ts
Labels: bugfix :bug: :white_check_mark:, small change :droplet:
